name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select branch to deploy from'
        required: true
        default: 'main'
        type: choice
        options:
          - main
          - staging
      environment:
        description: 'Select the environment to deploy to'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - staging

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      GLOBAL_VAR: "global"

    steps:
    - name: print branch and environment
      run: |
        echo "branch - ${{ github.event.inputs.branch }}"
        echo "env - ${{ github.event.inputs.environment }}"

    - name: print env variables
      run: echo 'homepage - ${{ vars.HOMEPAGE}}'

    - name: Set dynamic HOMEPAGE based on environment selection
      run: |
          if [ "${{ github.event.inputs.environment }}" == "development" ]; then
            echo "HOMEPAGE=https://dev@xyz.com" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.environment }}" == "staging" ]; then
            echo "HOMEPAGE=https://qa@xyz.com" >> $GITHUB_ENV
          fi
      
    - name: Print env domain
      run: |
        echo "selected env - $HOMEPAGE"
      
    - name: Pring global value
      run: echo "The job variable is ${{ env.GLOBAL_VAR }}"
      
    - name: Print step value
      env:
        STEP_VAR: "Step Value" 
      run: echo "The step variable is ${{ env.STEP_VAR }}"
