# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  schedule:
    - cron: '*/2 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Print env domain
      run: echo "selected env - ${{ secrets.DOMAIN }} - ${{ env.DOMAIN }}"
