# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Development package

on:
  push:
    branches:
      - main
      - staging

jobs:
  build:

    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'development' || 'staging' }}
    env:
      GLOBAL_VAR: "global"

    steps:
    - name: Print env domain
      run: echo "selected env - ${{ vars.HOMEPAGE }}"
      
    - name: Pring global value
      run: echo "The job variable is ${{ env.GLOBAL_VAR }}"
      
    - name: Print step value
      env:
        STEP_VAR: "Step Value" 
      run: echo "The step variable is ${{ env.STEP_VAR }}"
