# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  schedule:
    - cron: '* * * * *'
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    environment: development
    env:
      GLOBAL_VAR: ${{ secrets.DOMAIN }}

    steps:
    - name: Print env domain
      run: echo "selected env - ${{ vars.HOMEPAGE }}"
      
    - name: Pring global value
      run: echo "The job variable is ${{ env.GLOBAL_VAR }}"
      
    - name: Print step value
      env:
        STEP_VAR: "Step Value" 
      run: echo "The step variable is ${{ env.STEP_VAR }}"
